name: Deploy React App to IIS (Self-hosted)

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted  # 👈 this is important
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm install axios recharts

      - name: Build React app
        run: npm run build

      - name: Copy web.config to build folder
        run: copy web.config build\web.config
        shell: cmd

      - name: Deploy to IIS folder
        run: |
          if exist "C:\inetpub\wwwroot\reactapp" (
            rmdir /s /q "C:\inetpub\wwwroot\reactapp"
          )
          mkdir "C:\inetpub\wwwroot\reactapp"
          xcopy /s /e /y build\* "C:\inetpub\wwwroot\reactapp\"
        shell: cmd

      - name: ✅ Success
        run: echo "Deployed to IIS Successfully"
