name: Deploy React App to GitHub Pages and IIS

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          npm install axios recharts

      - name: Build React app
        run: npm run build

  deploy:
    runs-on: self-hosted  # 👈 Must be a Windows self-hosted runner
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: List build directory
        run: ls build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: build
          enable_jekyll: false
          publish_branch: gh-pages

      # - name: Deploy to IIS (Windows)
      #   run: |
      #     $iisPath = "C:\inetpub\wwwroot\reactapp"
      #     $sourcePath = "${{ github.workspace }}\build"

      #     if (Test-Path $iisPath) {
      #       Remove-Item "$iisPath\*" -Recurse -Force
      #     } else {
      #       New-Item -Path $iisPath -ItemType Directory -Force
      #     }

      #     Copy-Item "$sourcePath\*" -Destination $iisPath -Recurse -Force
      #   shell: pwsh

  notify-success:
    runs-on: ubuntu-latest
    needs: deploy
    if: success()

    steps:
      - name: Success
        run: echo "Deployment Successful!!!"

  notify-failure:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()

    steps:
      - name: Failure
        run: echo "Deployment Failed!!"

