name: Deploy React App to GitHub Pages

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: ./sidak_new

      - name: Build React app
        run: npm run build
        working-directory: ./sidak_new

      - name: List build output
        run: ls -R ./sidak_new

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./sidak_new/dist
          enable_jekyll: false
          publish_branch: gh-pages

  notify-success:
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    steps:
      - name: Success
        run: echo "Deployment Successfulll!!!"

  notify-failure:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    steps:
      - name: Failure
        run: echo "Deployment Failure!!"
